version: '3.5'

services:
  SmartLock-MQTT_Server:
    image: emqx/emqx:latest
    container_name: SmartLock-MQTT_Server
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083
      - 8081:8081
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
      - ./emqx/etc:/opt/emqx/etc
    restart: always

  SmartLock-DataBase:
    image: agrozyme/mariadb:latest
    container_name: SmartLock-DataBase
    volumes:
      - ./mySQL:/var/lib/mysql
    environment:
      - MYSQL_DATABASE = SmartLockDataBase
      - MYSQL_ROOT_PASSWORD = SmartLockDataBasePassword