version: "2.2"

services:
  nodered:
    # If you are running on RaspBerryPi change the image to
    # nodered/node-red-docker:rpi
    image: nodered/node-red-docker:latest  # 指定镜像版本
    container_name: nodered  # 命名容器
    restart: always # 在容器退出时总是重启容器
    network_mode: host # 共享主机的network namespace
    user: root # 指定当前用户
    ports:
      - "1880:1880" # 映射端口
    volumes:
      - "${PWD}/nodered:/data" # 数据文件持久化到宿主机位置
  mosquitto:
    image: eclipse-mosquitto:latest # 指定镜像版本
    container_name: mosquitto  # 命名容器
    restart: always # 在容器退出时总是重启容器
    network_mode: host # 共享主机的network namespace
    ports:
      - "1883:1883" # 映射端口
      - "9001:9001"
    volumes:
      - "${PWD}/mosquitto/conf:/mosquitto/config/" # 配置文件持久化到宿主机位置
      - "${PWD}/mosquitto/data/:/mosquitto/data/" # 数据文件持久化到宿主机位置
      - "${PWD}/mosquitto/log/:/mosquitto/log/" # 日志文件持久化到宿主机位置